export facts = [
  "El Atercurisaurus desarrolló mandíbulas reforzadas capaces de fracturar hueso compacto en segundos."
  "El Atercurisaurus presentaba cicatrices óseas que evidencian combates frecuentes entre individuos."
  "El Atercurisaurus evolucionó en aislamiento insular que intensificó su agresividad natural."
  "El Brontosaurus baxteri podía provocar vibraciones perceptibles en el suelo durante estampidas masivas."
  "El Brontosaurus baxteri mantenía grupos sociales organizados para proteger a sus crías."
  "El Brontosaurus baxteri era fundamental para mantener el equilibrio vegetal del ecosistema."
  "El Calcarisaurus ieiuniosus poseía espolones en las patas traseras que aumentaban su letalidad."
  "El Calcarisaurus ieiuniosus tenía un centro de gravedad bajo que mejoraba su estabilidad."
  "El Calcarisaurus ieiuniosus podía ejecutar giros rápidos sin perder tracción."
  "El Ferrucutus cerastes contaba con un blindaje dérmico compuesto por osteodermos resistentes."
  "El Ferrucutus cerastes prefería embestidas frontales antes que persecuciones prolongadas."
  "El Ferrucutus cerastes tenía un cráneo reforzado capaz de soportar impactos directos."
  "El Foetodon ferrus emitía un olor intenso que probablemente funcionaba como defensa química."
  "El Foetodon ferrus detectaba carroña a grandes distancias gracias a su olfato desarrollado."
  "El Foetodon ferrus solía aprovechar restos abandonados por depredadores mayores."
  "El Hebeosaurus torvus combinaba resistencia física con ataques explosivos."
  "El Hebeosaurus torvus tenía visión adaptada a entornos selváticos de baja luz."
  "El Hebeosaurus torvus utilizaba emboscadas desde zonas de vegetación densa."
  "El Indominus Rex integraba ADN de múltiples especies para potenciar su capacidad depredadora."
  "El Indominus Rex demostraba aprendizaje conductual tras cada enfrentamiento."
  "El Indominus Rex poseía una inteligencia superior a la de la mayoría de los terópodos."
  "El Ligocristus innocens sobrevivía gracias a una defensa colectiva altamente coordinada."
  "El Ligocristus innocens desarrolló piel engrosada como protección contra mordidas."
  "El Ligocristus innocens dependía de estampidas grupales como estrategia de supervivencia."
  "El Malevolusaurus perditor tenía una mordida diseñada para amputar extremidades."
  "El Malevolusaurus perditor presentaba dientes serrados ideales para desgarrar tejido."
  "El Malevolusaurus perditor atacaba preferentemente individuos aislados."
  "El Nefundusaurus accerbus mostraba una agresividad extrema incluso hacia su especie."
  "El Nefundusaurus accerbus tenía una notable resistencia a infecciones por heridas."
  "El Nefundusaurus accerbus sufría una alta mortalidad antes de alcanzar la adultez."
  "El Scimitodon sagax utilizaba garras curvadas para inmovilizar a sus presas."
  "El Scimitodon sagax mantenía equilibrio incluso durante combates violentos."
  "El Scimitodon sagax mostraba un comportamiento estratégico en la caza."
  "El Spinoceratops combinaba rasgos defensivos y ofensivos en un mismo cuerpo."
  "El Spinoceratops utilizaba su estructura ósea frontal para intimidar rivales."
  "El Spinoceratops equilibraba potencia mandibular con defensa estructural."
  "El Spinoraptor destacaba por su velocidad en distancias cortas."
  "El Spinoraptor tenía habilidades acuáticas superiores a otros híbridos."
  "El Spinoraptor poseía una gran capacidad de adaptación táctica."
  "El Stegoceratops contaba con placas óseas capaces de amortiguar impactos."
  "El Stegoceratops defendía a sus crías utilizando su cola como arma."
  "El Stegoceratops resistía múltiples ataques antes de colapsar."
  "El Vastatosaurus Rex desarrolló una fuerza mandibular superior a la de otros tiranosáuridos."
  "El Vastatosaurus Rex ocupaba el rol de superdepredador dominante en su entorno."
  "El Vastatosaurus Rex soportaba combates prolongados con gran tolerancia al dolor."
  "El Venatosaurus cazaba en grupos organizados con coordinación avanzada."
  "El Venatosaurus utilizaba vocalizaciones para sincronizar ataques."
  "El Venatosaurus ejecutaba estrategias envolventes similares a manadas modernas."
  "El Zeropteryx torova compensaba su tamaño con una gran capacidad de salto."
  "El Zeropteryx torova utilizaba embestidas rápidas para desorientar a sus oponentes."
]
