export facts = [
  "Aciedactylus is one of many theropod concept designs meant for King Kong that was eventually scrapped due to the large amount of similar looking theropod carnivores in the film. It would later be canonized in the The World of Kong book. As the theropod consumes more than just molluscs, but other hard-shelled organisms. The appetite and adaptations of Aciedactylus would have been called durophagy, which would make the dinosaur a durovore not a molluscivore."
  "Adlapsusaurus bears resemblance to Dilophosaurus and its hunting behaviour was similar to the now debunk hypothesis of Oviraptor."
  "Aetosaurs were a family of proto-crocodilomorphs that were nearly all largely comprised of herbivorous specimens and were almost all armoured in scutes and spikes."
  "Arsartis has killing-claws on its feet much like dromaeosaurs which hints at some sort of relation with Venatosaurus and Ambulaquasaurus."
  "Asperdorsus bellator its heavily armoured scutes and spiked appendages is also seen among several smaller-species of sauropods which need those adaptations to compensate for their smaller size, of which Asperdorsus clearly mimics."
  "Bifurcatops peritus has its body template and delicate frame mimics that of mountain goats and deers in a process of convergent evolution."
  "El Brontosaurus baxteri también es llamado bajo su segundo nombre científico, 'excelsus'."
  "In 2015, recent evidence discovered by paleontologists show that Brontosaurus is actually a separate dinosaur species, and not the same as the similar Apatosaurus as once thought for a while."
  "In the book 'The World of Kong: A Natural History of Skull Island' from 2005 Brontosaurus is described also as a species of dinosaur that gives live birth instead of laying eggs."
  "En 2015, evidencia reciente descubierta por paleontólogos muestra que Brontosaurus es en realidad una especie de dinosaurio separada, y no el mismo Apatosaurus, como se pensó durante un tiempo."
  "Realistically, none of the Brontosaurus would be able to run even in short distances due to the immense weight putting stress on its legs. Likewise, the front-feet of the Brontosaurus would not be like an elephant's, rather it resembled toeless tree-tunks that would have centered the weight distribution evenly."
  "Calcarisaurus its unknown what type of lizard it is, although it is likely a form of veranid due to its size. The lizard fills a niche equivalent to that of the ankylosaurids through convergent evolution."
  "Of the ceratopsians, the Chalyceratops seradorsus bears the most resemblance of the classic Triceratops from the classic King Kong film."
  "For all intents and purposes, Diablosaurus fulfills the niche of a rhinoceros to an uncanny degree."
  "By convergent evolution, Falcotops seems to have filled the niche of most storks and wading birds."
  "Along with the Foetodon, Ferrucutus cerastes don't appear in the videogame adaption."
  "The Ferrucutus in the extended version of the 2005 movie is male and named Sparkie."
  "Ferrucutus have a small tail and a big horns."
  "There were no Foetodon in the video game adaption, for an unknown reason."
  "Foetodon resembles Postosuchus, and may be based on the animal."
  "Formicarovo's long toes is also present in other water birds such as the aforementioned jacana. Combined with its low weight, the jacana is able to traverse on aquatic environments impossible for larger creatures."
  "Junto al Indoraptor, el Indominux Rex pertenecen a la familia ficticia denominada Chimeridae. Pese a ser la fuente base para el Indoraptor, son notablemente diferentes: el Indoraptor es más chico, más ágil, melánico y de sexo masculino, mientras que la Indominus rex es más grande, más pesada, albina y de sexo femenino. Además el Indoraptor parece mostrar más sadismo y un sentido del humor retorcido casi de caricatura."
  "Indominus Rex se parece mucho al Baryonyx o Suchomimus gigante llamado Rudy de la película La Era del Hielo 3: El origen de los dinosaurios."
  "El Indominus Rex presenta estructuras similares a protoplumas en sus brazos ya que recientes estudios a un terópodo carcharodontosarus de España llamado Concavenator presenta dichas estructuras, ademas de varios terópodos con plumas como el Velociraptor y el Therizinosaurus, inclusive puede que el T-Rex. Las garras y brazos largos parecen ser la impronta genética del Therizinosaurus según lo mencionado por el paleontologo y asesor de la película Jack Horner. Las espinas en el lomo de Indominus son semejantes a las encontradas en las impresiones de piel fósil de Carnotaurus."
  "El nombre Indoraptor significa 'Ladrón Indomable' ya que a diferencia del Indosuchus o el Indosaurus donde el término 'Indo' significa 'de la India', en el caso del Indoraptor es una abreviación de Indominus.Los colores, su desagradable aspecto y la forma en que acecha a sus victimas recuerdan mucho al monstruoso Xenomorfo de la película Alien."
  "El Indoraptor Tiene un andar cuadrúpedo mucho más marcado que su antecesor, Indominus Rex. Además de su inusual andar más cuadrúpedo, también rastrea a sus víctimas olfateando el suelo, lo cual es extraño e inusual, ya que ésta es una característica más canina lo cual recuerda al Deinonycanis."
  "En muchos aspectos, el Indoraptor es contrario a la Indominus Rex pese a tener su ADN, ya que la Indominus es albina, de sexo femenino, más fuerte y mataba por frustración ira y deporte. El Indoraptor es melánico, de sexo masculino, más ágil y mataba por diversión y sadismo."
  "El Indoraptor tiene algunas similitudes con la especie 'sornaensis' de velociraptor, pero podría ser pura coincidencia."
  "El Indoraptor está inspirado en algunos de los monstruos más conocidos del género de terror y comparte varias similitudes."
  "Given the fact that this species of hadrosaur has great swimming abilities, Ligocristus is one of the few species of Skull Island's megafauna that would have survived the 1948 earthquake without the need for human intervention. This species most likely would have swam to nearby islands."
  "The lack of any substantive change other than diet from their Dimetrodon ancestors makes Malevolusaurus a living fossil."
  "With the sheer amount of coastal predators, the Nefundusaurus would have most likely faced immense competition from similarly-built Aciedactylus and Tartarusaurus."
  "Nefundusaurus is one of many theropod concept designs meant for King Kong that was eventually scrapped due to the large amount of similar looking theropod carnivores in the film. It would later be canonized in the The World of Kong book."
  "Based on its feeding habits, its elongated finger claws and diet. Peracerdon might be a living relative to the Spinosaurids."
  "It is highly likely that Pugiodorsus is a diminutive descendant of ankylosaurids."
  "Purgiodorsus resemble the bipedal ankylosaurid Jakapil."
  "El Spinoceratops es el único de los cuatro dinosaurios híbridos del canon que no es hostil a los protagonistas debido a que su genoma básico es el de un herbívoro. Además, "Angel" y "Rebelde" son los únicos dinosaurios híbridos de la franquicia que han recibido nombres oficiales."
  "El Spinoceratops es el único dinosaurio híbrido del canon que no ha sido creado por Henry Wu."
  "Spinoceratops es el único híbrido representado exclusivamente como un bebé en el canon cinematográfico."
  "Spinoraptor proviene de la palabra raptor, que significa 'Ladrón', y de spino, que significa 'espinas'. Por lo tanto, significa 'Ladrón con espinas' o 'Ladrón Espinoso'."
  "El nombre Stegoceratops significa 'Rostro tejado con cuernos'."
  "Tartarusaurus has its ability to store fat in its tail is akin to the Gila Monster: a venomous lizard of the American southwest."
  "Tartarusaurus possesses large thumb-claws similar to the spinosaurs like Baryonyx."
  "Like Aciedactylus, Tartarusaurus is one of many theropod concept designs meant for King Kong that was eventually scrapped due to the large amount of similar looking theropod carnivores in the film. It would later be canonized in the The World of Kong book."
  "According to the creators of the 2005 film, King Kong; the Vastatosaurus Rex are direct descendants of the Tyrannosaurus; but they are much larger than their ancestors."
  "Due to the location of Skull Island, it is more likely that Vastatosaurus Rex descended from Tarbosaurus; instead of the Tyrannosaurus."
  "The Venatosaurus in the film resemble Utahraptor (a much larger Dromaeosaurid)."
  "Vultursaurus, like many other Skull Island creatures, has an entry in book 'The World of Kong: A Natural History of Skull Island' detailing its origin and biology."
  "Vultursaurus resembles the real-life bat-winged dinosaur Yi qi, which was discovered 10 years after World of Kong was published."
  "Although its name literally translates to zero wing, Zeropteryx clearly has defined wings in the artwork."
  "Its bald head and neck indicates that, like Brutornis, Zeropteryx fully gorge themselves within the belly of their prey. Given that they hunt animals many times their size like Ligocristus, this is not a surprise."
  "It is unknown how Zeropteryx can co-exist with Brutornis as both birds co-inhabit the same environment and prey selection, making niche partitioning incredibly difficult to assess without them going into conflict."
  "Like all animals from Skull Island. It is unknown what they faced during the sinking of the island. Given the multiple expeditions, there may be a chance that a few surviving populations was saved off-land to a more stable enclosure."
  "Although given its extremely difficult and specialised food source, ensuring their survival would have been an immense undertaking."
]
